CREATE TABLE [dbo].[business_metrics_gold] (

	[business_id] varchar(8000) NULL, 
	[name] varchar(8000) NULL, 
	[address] varchar(8000) NULL, 
	[city] varchar(8000) NULL, 
	[state] varchar(8000) NULL, 
	[postal_code] varchar(8000) NULL, 
	[latitude] float NULL, 
	[longitude] float NULL, 
	[stars] float NULL, 
	[review_count] int NULL, 
	[is_open] int NULL, 
	[categories] varchar(8000) NULL, 
	[_ingest_ts] datetime2(6) NULL, 
	[review_count_total] bigint NULL, 
	[avg_rating] float NULL, 
	[rating_std] float NULL, 
	[first_review_date] date NULL, 
	[last_review_date] date NULL, 
	[useful_votes_total] bigint NULL, 
	[funny_votes_total] bigint NULL, 
	[cool_votes_total] bigint NULL, 
	[active_days] int NULL, 
	[active_years] float NULL, 
	[reviews_per_year] float NULL, 
	[business_popularity_tier] varchar(8000) NULL, 
	[rating_bucket] varchar(8000) NULL, 
	[_gold_build_ts] datetime2(6) NULL
);