CREATE TABLE [dbo].[user_bronze] (

	[average_stars] float NULL, 
	[compliment_cool] bigint NULL, 
	[compliment_cute] bigint NULL, 
	[compliment_funny] bigint NULL, 
	[compliment_hot] bigint NULL, 
	[compliment_list] bigint NULL, 
	[compliment_more] bigint NULL, 
	[compliment_note] bigint NULL, 
	[compliment_photos] bigint NULL, 
	[compliment_plain] bigint NULL, 
	[compliment_profile] bigint NULL, 
	[compliment_writer] bigint NULL, 
	[cool] bigint NULL, 
	[elite] varchar(8000) NULL, 
	[fans] bigint NULL, 
	[friends] varchar(8000) NULL, 
	[funny] bigint NULL, 
	[name] varchar(8000) NULL, 
	[review_count] bigint NULL, 
	[useful] bigint NULL, 
	[user_id] varchar(8000) NULL, 
	[yelping_since] varchar(8000) NULL, 
	[_ingest_ts] datetime2(6) NULL, 
	[_source_file] varchar(8000) NULL, 
	[_batch_id] varchar(8000) NULL
);