CREATE TABLE [dbo].[user_silver] (

	[user_id] varchar(8000) NULL, 
	[name] varchar(8000) NULL, 
	[review_count] int NULL, 
	[average_stars] float NULL, 
	[fans] int NULL, 
	[_ingest_ts] datetime2(6) NULL, 
	[_source_file] varchar(8000) NULL, 
	[yelping_since] varchar(8000) NULL, 
	[useful] int NULL, 
	[funny] int NULL, 
	[cool] int NULL, 
	[friends] varchar(8000) NULL, 
	[elite] varchar(8000) NULL, 
	[compliment_cool] int NULL, 
	[compliment_cute] int NULL, 
	[compliment_funny] int NULL, 
	[compliment_hot] int NULL, 
	[compliment_list] int NULL, 
	[compliment_more] int NULL, 
	[compliment_note] int NULL, 
	[compliment_photos] int NULL, 
	[compliment_plain] int NULL, 
	[compliment_profile] int NULL, 
	[compliment_writer] int NULL, 
	[_batch_id] varchar(8000) NULL
);